# Generated by Django 4.2.6 on 2024-10-05 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(max_length=511)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.CharField(max_length=127)),
                ('district', models.CharField(max_length=127)),
                ('num_likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_comments', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('park_image_1', models.ImageField(upload_to='static/images/park_images')),
                ('park_image_2', models.ImageField(blank=True, null=True, upload_to='static/images/park_images')),
                ('park_image_3', models.ImageField(blank=True, null=True, upload_to='static/images/park_images')),
                ('park_video', models.FileField(blank=True, null=True, upload_to='static/videos/park_videos')),
                ('availability', models.BooleanField(default=True)),
                ('work_hours_start', models.TimeField(blank=True, null=True)),
                ('work_hours_end', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parks.park')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parks.park')),
            ],
        ),
    ]
